theme: jekyll-theme-minimal
title: Marilena Lemonari' homepage
description: Γειά σας, I am Marilena Lemonari is a second-year PhD student of Computer Science at the University of Cyprus (UCY) under CLIPE, a Horizon Marie-Curie ITN project.
Before that, Ι was awarded my MSc in Machine Learning from UCL (2020).
In 2019, Ι received my BSc in Mathematics from the University of Nottingham.
Recently, Ι have completed my 3-month secondment at Inria as a research guest, during which, she has worked on intuitive control for characters and small groups. 
As an Early-Stage Researcher (ESR) for CLIPE, my research interests revolve around crowd control and authoring, machine learning for computer graphics and behavioural crowd simulation.
